let Word = require("./word");
let inquirer = require("inquirer");

let wordArr = [
    "Dark Matter",
    "Orphan Black",
    "Star Trek: Voyager",
    "Torchwood",
    "Farscape",
    "Futurama",
    "Babylon 5",
    "The Expanse",
    "Westworld",
    "Stranger Things",
    "Mystery Science Theater 3000",
    "Fringe",
    "Star Trek: Deep Space Nine",
    "Stargate SG-1",
    "Lost",
    "Firefly",
    "Star Trek",
    "The Twilight Zone",
    "Battlestar Galactica",
    "Star Trek: The Next Generation",
    "The X-Files",
    "Doctor Who",
    "Stargate Atlantis",
    "Stargate Universe",
    "Killjoys",
    "Buffy the Vampire Slayer",
    "Angel",
    "Defiance",
    "Dollhouse",
    "The Outer Limits",
    "Quantum Leap",
    "Continuum",
    "The Man in the High Castle",
    "The Orville",
    "Warehouse 13",
    "Eureka",
    "Game of Thrones",
    "Star Trek: Enterprise",
    "Star Trek: Discovery",
    "Falling Skies",
    "Altered Carbon",
    "Colony",
    "Black Mirror",
    "Caprica",
    "Sense8",
    "Rick and Morty",
    "Counterpart",
    "Humans",
    "Sanctuary",
    "Andromeda"
];
let randomIndex = Math.floor(Math.random() * wordArr.length);